services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: labseq
      POSTGRES_PASSWORD: labseq
      POSTGRES_DB: labseq
    ports:
      - "5434:5432"
    volumes:
      - labseq_pg:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U labseq -d labseq"]
      interval: 3s
      timeout: 5s
      retries: 20

  api:
    build: ./backend
    environment:
      DATABASE_URL: postgresql+psycopg2://labseq:labseq@db:5432/labseq
      SEED_ON_EMPTY: "true"
    ports:
      - "8200:8200"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    ports:
      - "3200:80"
    depends_on:
      - api

volumes:
  labseq_pg:
